include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    prefer_const_declarations: ignore
    prefer_const_constructors: ignore
    argument_type_not_assignable: ignore
    flutter_style_todos: ignore
    sort_pub_dependencies: ignore
    asset_does_not_exist: ignore
    cascade_invocations: ignore
    avoid_print: ignore
    one_member_abstracts: ignore

linter:
  rules:
    prefer_const_literals_to_create_immutables: false
    public_member_api_docs: false
