include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    prefer_const_declarations: ignore
    prefer_const_constructors: ignore
    argument_type_not_assignable: ignore
    flutter_style_todos: ignore
    sort_pub_dependencies: ignore

linter:
  rules:
    # todo: リリース前にはtrueにする
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    require_trailing_commas: true
    public_member_api_docs: false
