analyzer:
  errors:
    prefer_const_declarations: ignore
    prefer_const_constructors: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # todo: リリース前にはtrueにする
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    require_trailing_commas: true


