name: kimikoe_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # riverpod
  flutter_riverpod: ^2.5.1
  # supabase
  supabase_flutter: ^2.5.1
  flutter_dotenv: ^5.2.1
  # OAuth
  google_sign_in: ^6.2.1
  # other
  flutter_svg: ^2.0.14
  flutter_datetime_picker_plus: ^2.2.0
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.1
  gap: ^3.0.1
  go_router: ^14.2.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.5.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.3
  collection: ^1.19.0
  youtube_player_iframe: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.7.0
  mockito: ^5.4.4
  url_launcher_platform_interface: ^2.3.2
  plugin_platform_interface: ^2.1.8
  matcher: ^0.12.16+1
  very_good_analysis: ^6.0.0
  mock_supabase_http_client: ^0.0.3+1
  robot: ^0.1.3
  path_provider: ^2.1.5

flutter:
  uses-material-design: true
  assets: 
      - .env
      - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/kimikoe_app_icon.png"
  adaptive_icon_foreground: "assets/images/kimikoe_app_icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/kimikoe_app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
