name: Flutter Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # リポジトリのコードをクローン
      
      # .envファイルを作りGithubActionsシークレットに登録した環境変数を.envに書き込む
      - name: Create .env file
        run: |
          touch .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "GOOGLE_OAUTH_IOS_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_IOS_CLIENT_ID }}" >> .env
          echo "GOOGLE_OAUTH_WEB_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_WEB_CLIENT_ID }}" >> .env

      # Flutter SDKのキャッシュ
      - name: Cache Flutter SDK 
        uses: actions/cache@v3 
        with: 
          path: /opt/hostedtoolcache/flutter 
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }} 
          restore-keys: | 
            ${{ runner.os }}-flutter-

      - uses: subosito/flutter-action@v2 
        with: 
          flutter-version: '3.24.0' # latestはダメだった

      # 依存関係のキャッシュ
      - name: Cache dependencies 
        uses: actions/cache@v3 
        with: 
          path:
            ~/.pub-cache
            ~/.flutter 
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }} 
          restore-keys: | 
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get
      
      - name: Check for outdated dependencies 
        run: flutter pub outdated

      # アンドロイドエミュレータの環境を構築 
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Java 
        uses: actions/setup-java@v4 
        with: 
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Android Emulator and Integration Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/main_test.dart

      # コードチェック、テスト
      - name: Check Code Formatting 
        run: dart format .
  
      - name: Analyze project source
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --coverage

      - name: Run unit tests
        run: flutter test integration_test/main_test.dart --coverage
        
      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v5
        with: 
          file: ./coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: miz8462/kimikoe