name: Flutter Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # リポジトリのコードをクローン

      # Flutter SDKのインストール 
      - uses: subosito/flutter-action@v2 
        with: 
          flutter-version: '3.24.0' # latestはダメだった

      - name: Install dependencies
        run: flutter pub get
  
      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test --machine > test_results.json 
        
      - name: Upload test results 
        uses: actions/upload-artifact@v3 
        with: 
          name: test-results 
          path: test_results.json 
